//! Cutter Grid verification, tested against a trajectory the real planner made.
//!
//! The fixture is the output of `planCutterGridLadderTrajectory` on the shipped
//! challenge, generated by `tools/generate-cutter-grid-plan.ts` in the frontend
//! repository. That matters: a synthetic plan would only prove the verifier
//! agrees with whatever this file's author imagined a trajectory looks like,
//! whereas the certified reference program has an *independently known* correct
//! answer — it cuts exactly the twelve target voxels and nothing else, for a
//! completion score of 100.
//!
//! The tampering tests all take that same valid plan and break one thing. A check
//! that never rejects anything passes every "it accepts a good plan" test ever
//! written, so each audit needs a case that proves it can say no.

use hcr_contract::*;
use hcr_sim::*;

const PLAN_FIXTURE: &str = include_str!("fixtures/cutter-grid-plan-v2.json");
const VECTORS: &str = include_str!("fixtures/vectors.json");

/// The challenge the server serves, from the same fixture `hcr` seeds
/// its catalog from.
fn shipped_challenge() -> ChallengeDefinition {
    let vectors: serde_json::Value = serde_json::from_str(VECTORS).expect("vectors parse");
    serde_json::from_value(vectors["challenge"].clone()).expect("challenge parses")
}

fn submission() -> CutterGridSubmission {
    serde_json::from_str(PLAN_FIXTURE).expect("plan fixture parses")
}

/// The fixture as raw JSON, for tests that need to corrupt a field before it is
/// ever typed.
fn submission_json() -> serde_json::Value {
    serde_json::from_str(PLAN_FIXTURE).expect("plan fixture parses")
}

fn from_json(value: serde_json::Value) -> CutterGridSubmission {
    serde_json::from_value(value).expect("tampered fixture still parses")
}

fn expect_rejection(submission: &CutterGridSubmission) -> (CutterRejection, Option<String>) {
    let challenge = shipped_challenge();
    match verify_and_replay(&challenge, submission, CutterReplayOptions::default()) {
        Err(SimError::CutterPlanRejected {
            rejection,
            source_block_id,
            ..
        }) => (rejection, source_block_id),
        Err(other) => panic!("expected a plan rejection, got {other:?}"),
        Ok(_) => panic!("expected a rejection, but the plan was accepted"),
    }
}

// ---------------------------------------------------------------------------
// The happy path
// ---------------------------------------------------------------------------

/// The certified reference program cuts exactly what the challenge asks for.
///
/// This is the anchor: the profile's own certification records that this route
/// removes the twelve target voxels with no collateral damage, so a completion
/// score of anything but 100 means the server's sweep disagrees with the
/// browser's about what the tool touched.
#[test]
fn the_reference_program_scores_a_perfect_cut() {
    let challenge = shipped_challenge();
    let outcome = verify_and_replay(&challenge, &submission(), CutterReplayOptions::default())
        .expect("the certified reference trajectory must verify");

    assert_eq!(
        outcome.replay.score.completion_score, 100.0,
        "reference program should cut exactly the target"
    );
    assert_eq!(outcome.replay.terminal.reason, TerminalReason::Completed);
    assert_eq!(
        outcome.replay.remaining_voxels.len(),
        challenge.target_hair.voxels.len(),
        "hair left standing should be the target hairstyle"
    );
}

/// Command count is the server's own expansion, and it is per *cell*.
///
/// The reference program is nine `move` blocks totalling 22 cells. A server that
/// counted blocks would report 9 and quietly make long moves free.
#[test]
fn commands_are_counted_per_cell_not_per_block() {
    let challenge = shipped_challenge();
    let submission = submission();
    assert_eq!(submission.program.nodes.len(), 9, "fixture shape changed");

    let outcome =
        verify_and_replay(&challenge, &submission, CutterReplayOptions::default()).unwrap();
    assert_eq!(outcome.replay.metrics.executed_command_count, 22);
}

/// The client's numbers agreed with the server's.
#[test]
fn a_faithful_client_does_not_diverge() {
    let challenge = shipped_challenge();
    let outcome =
        verify_and_replay(&challenge, &submission(), CutterReplayOptions::default()).unwrap();

    assert!(
        !outcome.divergence.diverged(),
        "planner and verifier disagreed: {:?}",
        outcome.divergence
    );
    assert_eq!(outcome.divergence.result_voxels_match, Some(true));
}

/// Expansion is the server's, so a lying `executedCommandCount` changes nothing
/// but the divergence report.
///
/// It is deliberately *not* a rejection: the field is advisory, and refusing a
/// submission over it would turn a telemetry signal into an outage the first time
/// the two expanders disagreed about something harmless.
#[test]
fn a_wrong_client_command_count_is_reported_not_enforced() {
    let mut json = submission_json();
    json["plan"]["executedCommandCount"] = serde_json::json!(1);

    let challenge = shipped_challenge();
    let outcome =
        verify_and_replay(&challenge, &from_json(json), CutterReplayOptions::default()).unwrap();

    assert!(!outcome.divergence.command_count_matches);
    assert!(outcome.divergence.diverged());
    assert_eq!(outcome.replay.metrics.executed_command_count, 22);
}

// ---------------------------------------------------------------------------
// Expansion
// ---------------------------------------------------------------------------

#[test]
fn moves_expand_one_action_per_cell() {
    let program = CutterGridProgram {
        kind: "cutter-grid".into(),
        version: 1,
        planner_version: CUTTER_GRID_LADDER_PLANNER_VERSION.into(),
        nodes: vec![CutterGridNode::Move {
            direction: CutterGridDirection::Right,
            distance: 4,
            source_block_id: "a".into(),
        }],
        source_block_count: 1,
    };
    let actions = expand_cutter_program(&program, MAX_RUNTIME_COMMANDS).unwrap();
    assert_eq!(actions.len(), 4);
}

#[test]
fn repeat_multiplies_the_body() {
    let program = CutterGridProgram {
        kind: "cutter-grid".into(),
        version: 1,
        planner_version: CUTTER_GRID_LADDER_PLANNER_VERSION.into(),
        nodes: vec![CutterGridNode::Repeat {
            count: 3,
            body: vec![
                CutterGridNode::Move {
                    direction: CutterGridDirection::Up,
                    distance: 2,
                    source_block_id: "a".into(),
                },
                CutterGridNode::Wait {
                    duration_ms: 100.0,
                    source_block_id: "b".into(),
                },
            ],
            source_block_id: "r".into(),
        }],
        source_block_count: 3,
    };
    let actions = expand_cutter_program(&program, MAX_RUNTIME_COMMANDS).unwrap();
    assert_eq!(actions.len(), 9, "3 x (2 cells + 1 wait)");
}

/// The cap applies to the expansion, which is the whole reason the server does
/// its own. A `repeat 20` around `move 12` is two blocks and 240 commands.
#[test]
fn the_command_cap_applies_after_expansion() {
    let program = CutterGridProgram {
        kind: "cutter-grid".into(),
        version: 1,
        planner_version: CUTTER_GRID_LADDER_PLANNER_VERSION.into(),
        nodes: vec![CutterGridNode::Repeat {
            count: 20,
            body: vec![CutterGridNode::Move {
                direction: CutterGridDirection::Right,
                distance: 12,
                source_block_id: "inner".into(),
            }],
            source_block_id: "r".into(),
        }],
        source_block_count: 2,
    };

    match expand_cutter_program(&program, 100) {
        Err(SimError::CommandLimitExceeded {
            limit,
            source_block_id,
        }) => {
            assert_eq!(limit, 100);
            assert_eq!(source_block_id, "inner", "should blame the move, not the repeat");
        }
        other => panic!("expected the cap to trip, got {other:?}"),
    }
}

#[test]
fn an_empty_program_is_refused() {
    let program = CutterGridProgram {
        kind: "cutter-grid".into(),
        version: 1,
        planner_version: CUTTER_GRID_LADDER_PLANNER_VERSION.into(),
        nodes: vec![],
        source_block_count: 0,
    };
    assert!(matches!(
        expand_cutter_program(&program, MAX_RUNTIME_COMMANDS),
        Err(SimError::EmptyProgram)
    ));
}

// ---------------------------------------------------------------------------
// Tampering — one broken claim per test
// ---------------------------------------------------------------------------

/// Planning against a different arm must not be scorable against this one.
#[test]
fn a_plan_for_another_challenge_is_refused() {
    let mut json = submission_json();
    json["plan"]["challengeSignature"] = serde_json::json!("0000000000000000");

    let (rejection, _) = expect_rejection(&from_json(json));
    assert_eq!(rejection, CutterRejection::SignatureMismatch);
}

/// The same guard from the other side: leave the plan alone and widen the arm.
///
/// This is the case that protects a live deployment. Retuning joint travel is an
/// ordinary content change, and without the signature every trajectory planned
/// before it would keep scoring — against an arm that no longer exists.
#[test]
fn editing_the_challenge_invalidates_existing_plans() {
    let mut challenge = shipped_challenge();
    challenge.robot_config.joints[0].max_angle_deg += 5.0;

    match verify_and_replay(&challenge, &submission(), CutterReplayOptions::default()) {
        Err(SimError::CutterPlanRejected { rejection, .. }) => {
            assert_eq!(rejection, CutterRejection::SignatureMismatch);
        }
        other => panic!("expected a signature mismatch, got {other:?}"),
    }
}

/// A short program with a long trajectory would be 22 cells of cutting billed as
/// one command.
#[test]
fn a_program_shorter_than_its_trajectory_is_refused() {
    let mut json = submission_json();
    json["program"]["nodes"] = serde_json::json!([{
        "type": "move",
        "direction": "left",
        "distance": 1,
        "sourceBlockId": "reference-1",
    }]);

    let (rejection, _) = expect_rejection(&from_json(json));
    assert_eq!(rejection, CutterRejection::StepMismatch);
}

/// Direction is part of the claim: `left` in the program must not be `right` in
/// the trajectory.
#[test]
fn a_step_that_contradicts_its_program_direction_is_refused() {
    let mut json = submission_json();
    // The program's first block moves left three cells; make the trajectory's
    // first step go right instead, leaving everything else intact.
    json["plan"]["steps"][0]["endCoord"] = serde_json::json!([1, 0, 0]);

    let (rejection, block) = expect_rejection(&from_json(json));
    assert_eq!(rejection, CutterRejection::CoordDiscontinuity);
    assert_eq!(block.as_deref(), Some("reference-1"));
}

/// Cells are entered one at a time.
#[test]
fn skipping_a_cell_is_refused() {
    let mut json = submission_json();
    json["plan"]["steps"][0]["endCoord"] = serde_json::json!([-2, 0, 0]);

    let (rejection, _) = expect_rejection(&from_json(json));
    assert_eq!(rejection, CutterRejection::CoordDiscontinuity);
}

/// The declared tip must be where the angles put it.
///
/// Without this the trajectory's geometry and its kinematics could describe two
/// different motions, and the sweep would follow whichever the server trusted.
#[test]
fn a_tip_position_that_contradicts_its_joint_angles_is_refused() {
    let mut json = submission_json();
    json["plan"]["steps"][0]["waypoints"][0]["endEffector"] = serde_json::json!([9.0, 9.0, 9.0]);

    let (rejection, block) = expect_rejection(&from_json(json));
    assert_eq!(rejection, CutterRejection::EndEffectorMismatch);
    assert_eq!(block.as_deref(), Some("reference-1"));
}

/// An angle past the joint's travel is not a pose the arm has.
#[test]
fn an_out_of_range_joint_angle_is_refused() {
    let mut json = submission_json();
    json["plan"]["steps"][0]["waypoints"][0]["jointAngles"]["baseYaw"] = serde_json::json!(400.0);

    let challenge = shipped_challenge();
    match verify_and_replay(&challenge, &from_json(json), CutterReplayOptions::default()) {
        Err(SimError::AngleOutOfRange { joint_id, .. }) => assert_eq!(joint_id, "baseYaw"),
        other => panic!("expected an out-of-range angle, got {other:?}"),
    }
}

/// A move that reaches the right cell by an arc through the hairstyle cuts
/// everything on the way. Endpoints alone do not constrain the middle.
///
/// The spliced waypoint is a **real pose from the far end of the same plan**, so
/// it passes every other audit: its angles are in range, its declared tip agrees
/// with forward kinematics, and it is clear of the head. Only its position
/// relative to this step's straight line is wrong — which is exactly the one
/// thing this check exists to catch, and nothing else would have caught it.
#[test]
fn a_move_that_detours_off_its_axis_is_refused() {
    let plan = submission().plan;
    let elsewhere = plan
        .steps
        .last()
        .unwrap()
        .waypoints
        .last()
        .unwrap()
        .clone();

    let mut json = submission_json();
    let middle = plan.steps[0].waypoints.len() / 2;
    json["plan"]["steps"][0]["waypoints"][middle]["jointAngles"] =
        serde_json::to_value(&elsewhere.joint_angles).unwrap();
    json["plan"]["steps"][0]["waypoints"][middle]["endEffector"] =
        serde_json::to_value(elsewhere.end_effector).unwrap();

    let (rejection, block) = expect_rejection(&from_json(json));
    assert_eq!(rejection, CutterRejection::PathDeviation);
    assert_eq!(block.as_deref(), Some("reference-1"));
}

/// Waypoints outlasting the step would cut on time nobody was charged for.
#[test]
fn a_step_whose_waypoints_outlast_its_duration_is_refused() {
    let mut json = submission_json();
    json["plan"]["steps"][0]["durationMs"] = serde_json::json!(1.0);

    let (rejection, block) = expect_rejection(&from_json(json));
    assert_eq!(rejection, CutterRejection::TimelineInvalid);
    assert_eq!(block.as_deref(), Some("reference-1"));
}

/// A V1 asset must not be replayed under V2's reachability rules.
#[test]
fn a_plan_from_the_old_planner_is_refused() {
    let mut json = submission_json();
    json["plan"]["plannerVersion"] = serde_json::json!("cutter-grid-dls-v1");

    let (rejection, _) = expect_rejection(&from_json(json));
    assert_eq!(rejection, CutterRejection::UnsupportedPlanVersion);
}

/// The waypoint ceiling is a cost guard, and it has to actually bite.
#[test]
fn an_oversized_plan_is_refused_before_it_is_verified() {
    let challenge = shipped_challenge();
    let options = CutterReplayOptions {
        max_waypoints: 10,
        ..CutterReplayOptions::default()
    };
    match verify_and_replay(&challenge, &submission(), options) {
        Err(SimError::CutterPlanRejected { rejection, .. }) => {
            assert_eq!(rejection, CutterRejection::TooManyWaypoints);
        }
        other => panic!("expected the waypoint ceiling to trip, got {other:?}"),
    }
}

/// The entry is free, so it must also be harmless.
///
/// Splicing the program's own first step onto the entry gives a motion that
/// certainly cuts — and would do it before the clock starts, attributed to no
/// block.
#[test]
fn an_entry_that_cuts_hair_is_refused() {
    let plan = submission().plan;
    let mut json = submission_json();

    // Append a cutting step's waypoints to the positioning trajectory. Every
    // pose in it is legal on its own; only the fact that it removes hair is
    // wrong, which is precisely the check under test.
    let mut entry = plan.positioning_trajectory.clone();
    entry.extend(plan.steps.last().unwrap().waypoints.iter().cloned());
    json["plan"]["positioningTrajectory"] = serde_json::to_value(&entry).unwrap();

    let (rejection, _) = expect_rejection(&from_json(json));
    assert_eq!(rejection, CutterRejection::EntryCutsHair);
}
