//! Server-owned Cutter Grid V4 planning profiles and bounded execution.
//!
//! This module deliberately has no scoring, session, match, Electron, or
//! ArmDock integration. It accepts only the compact V4 Program, resolves the
//! Challenge and certified Profile inside the service, and delegates the pure
//! planning work to `hcr_sim` on a bounded blocking pool.

use std::collections::HashMap;
use std::sync::{Arc, RwLock};
use std::time::Instant;

use hcr_contract::{
    CUTTER_GRID_PLAN_API_VERSION, ChallengeDefinitionDto, CutterGridPlanResponseV1,
    CutterGridPlanningErrorCodeV4, CutterGridPlanningStageV4, CutterGridProfileV4,
    CutterGridProgramV4,
};
use hcr_sim::{
    CutterGridCompileErrorV4, CutterGridPlanningFailureV4, compile_cutter_grid_program_v4,
    plan_cutter_grid_v4,
};
use tokio::sync::Semaphore;

use crate::error::{ServiceError, ServiceResult};

/// Distinguishes the production Rust implementation in V4 responses.
pub const CUTTER_GRID_RUST_PLANNER_IMPLEMENTATION: &str = "hcr-sim-rust";
/// Build identifier for planning diagnostics, intentionally absent from plan signatures.
pub const CUTTER_GRID_RUST_PLANNER_BUILD: &str = concat!("hcr/", env!("CARGO_PKG_VERSION"));

// Generated by the frontend's `npm run cutter-grid:profile` and committed as a
// versioned certification vector. The service consumes it at build time; HTTP
// callers can never supply, alter, or select a Profile body.
const BUNDLED_NEAT_SHORT_PROFILE_V4: &str =
    include_str!("../../../../HCR_Simulator_Frontend/tests/fixtures/cutter-grid-profile-v4.json");
const BUNDLED_NEAT_SHORT_CHALLENGE_ID: &str = "neat-short-cap";
const BUNDLED_NEAT_SHORT_CHALLENGE_VERSION: u32 = 1;

type ProfileKey = (String, u32, String);

/// A read-only registry of server-owned certified V4 Profiles.
#[derive(Debug, Default)]
pub struct CutterGridProfileRegistry {
    profiles: RwLock<HashMap<ProfileKey, Arc<CutterGridProfileV4>>>,
}

impl CutterGridProfileRegistry {
    /// Empty registry: challenges without an explicitly registered Profile fail closed.
    pub fn new() -> Self {
        Self::default()
    }

    /// Registry with the sole currently certified `Neat Short Haircut` V4
    /// Profile. A malformed bundled asset leaves the registry empty, so the
    /// only possible runtime outcome is fail-closed `planner-not-ready`.
    pub fn with_bundled_profiles() -> Self {
        let registry = Self::new();
        let _ = registry.register_bundled_neat_short_profile();
        registry
    }

    /// Decode and register the checked-in V4 certification asset.
    pub fn register_bundled_neat_short_profile(&self) -> ServiceResult<()> {
        let profile = serde_json::from_str(BUNDLED_NEAT_SHORT_PROFILE_V4).map_err(|_| {
            ServiceError::Internal("bundled Cutter Grid V4 Profile cannot be decoded")
        })?;
        self.register(
            BUNDLED_NEAT_SHORT_CHALLENGE_ID,
            BUNDLED_NEAT_SHORT_CHALLENGE_VERSION,
            profile,
        )
    }

    /// Register one immutable Profile for one immutable Challenge version.
    pub fn register(
        &self,
        challenge_id: impl Into<String>,
        challenge_version: u32,
        profile: CutterGridProfileV4,
    ) -> ServiceResult<()> {
        if profile.profile_signature.is_empty()
            || profile.challenge_signature.is_empty()
            || !profile.certification.passed
        {
            return Err(ServiceError::Internal(
                "refusing an uncertified Cutter Grid V4 Profile",
            ));
        }
        let key = (
            challenge_id.into(),
            challenge_version,
            profile.challenge_signature.clone(),
        );
        let mut profiles = self
            .profiles
            .write()
            .map_err(|_| ServiceError::Internal("Cutter Grid Profile lock poisoned"))?;
        if profiles.contains_key(&key) {
            return Err(ServiceError::Internal(
                "refusing to overwrite a Cutter Grid V4 Profile",
            ));
        }
        profiles.insert(key, Arc::new(profile));
        Ok(())
    }

    /// Resolve the Profile belonging to the server's own Challenge definition.
    pub fn profile_for(
        &self,
        challenge: &ChallengeDefinitionDto,
    ) -> ServiceResult<Arc<CutterGridProfileV4>> {
        let key = (
            challenge.challenge.id.clone(),
            challenge.meta.version,
            hcr_contract::cutter_grid_challenge_signature_v2(&challenge.challenge),
        );
        self.profiles
            .read()
            .map_err(|_| ServiceError::Internal("Cutter Grid Profile lock poisoned"))?
            .get(&key)
            .cloned()
            .ok_or_else(planner_not_ready)
    }

    /// Number of registered immutable Profile versions.
    pub fn len(&self) -> usize {
        self.profiles
            .read()
            .map(|profiles| profiles.len())
            .unwrap_or(0)
    }
}

/// Result produced by the bounded blocking planner before HTTP serialization.
#[derive(Debug, Clone)]
pub struct CutterGridPlannedResponse {
    /// Plan-response DTO ready for the route.
    pub response: CutterGridPlanResponseV1,
}

/// Independent bounded CPU pool for server-side V4 planning.
#[derive(Debug)]
pub struct CutterGridPlannerPool {
    permits: Arc<Semaphore>,
    profiles: Arc<CutterGridProfileRegistry>,
}

impl CutterGridPlannerPool {
    /// Construct a planner that allows at most `concurrency` in-flight searches.
    pub fn new(concurrency: usize, profiles: Arc<CutterGridProfileRegistry>) -> Self {
        Self {
            permits: Arc::new(Semaphore::new(concurrency.max(1))),
            profiles,
        }
    }

    /// Production default: two potentially expensive global graph searches.
    pub fn with_default_concurrency(profiles: Arc<CutterGridProfileRegistry>) -> Self {
        Self::new(2, profiles)
    }

    /// Expose the immutable Profile store for bootstrap registration only.
    pub fn profiles(&self) -> &Arc<CutterGridProfileRegistry> {
        &self.profiles
    }

    /// Resolve, compile and plan one V4 Program without blocking the async runtime.
    pub async fn plan(
        &self,
        challenge: &ChallengeDefinitionDto,
        program: &CutterGridProgramV4,
    ) -> ServiceResult<CutterGridPlannedResponse> {
        let profile = self.profiles.profile_for(challenge)?;
        let permit = Arc::clone(&self.permits)
            .try_acquire_owned()
            .map_err(|_| ServiceError::RateLimited)?;
        let challenge = challenge.challenge.clone();
        let program = program.clone();
        let profile_signature = profile.profile_signature.clone();
        let started = Instant::now();
        let plan = tokio::task::spawn_blocking(move || {
            let _permit = permit;
            let compiled =
                compile_cutter_grid_program_v4(&program).map_err(compile_failure_to_service)?;
            plan_cutter_grid_v4(&challenge, &compiled, &profile)
                .map_err(planning_failure_to_service)
        })
        .await
        .map_err(|_| ServiceError::Internal("Cutter Grid planning task failed to complete"))??;
        Ok(CutterGridPlannedResponse {
            response: CutterGridPlanResponseV1 {
                kind: "cutter-grid-plan-result".into(),
                version: CUTTER_GRID_PLAN_API_VERSION,
                planner_implementation: CUTTER_GRID_RUST_PLANNER_IMPLEMENTATION.into(),
                planner_build: CUTTER_GRID_RUST_PLANNER_BUILD.into(),
                profile_signature,
                planning_duration_ms: started.elapsed().as_secs_f64() * 1_000.0,
                plan,
            },
        })
    }
}

fn compile_failure_to_service(error: CutterGridCompileErrorV4) -> ServiceError {
    ServiceError::ProgramInvalid {
        message: format!("Invalid Cutter Grid V4 program: {}.", error.code.as_str()),
        field: error.source_block_id,
    }
}

fn planning_failure_to_service(error: CutterGridPlanningFailureV4) -> ServiceError {
    ServiceError::TrajectoryPlanningFailed {
        planner_code: error.code,
        stage: error.stage,
        field: error.source_block_id,
        action_index: error.action_index,
        expanded_action_index: error.expanded_action_index,
        target_coord: error.target_coord,
    }
}

fn planner_not_ready() -> ServiceError {
    ServiceError::TrajectoryPlanningFailed {
        planner_code: CutterGridPlanningErrorCodeV4::PlannerNotReady,
        stage: CutterGridPlanningStageV4::Profile,
        field: None,
        action_index: None,
        expanded_action_index: None,
        target_coord: None,
    }
}
