#!/bin/sh
# Generate nginx real-IP configuration for Cloudflare's ranges.
#
#   sudo sh deploy/cloudflare-realip.sh > /www/server/nginx/conf/cloudflare-realip.conf
#   sudo nginx -t && sudo nginx -s reload
#
# Behind Cloudflare, `$remote_addr` is a Cloudflare edge address, not the
# visitor's. Two things break as a result:
#
#   * `limit_req` keys every request to a handful of addresses, so the rate
#     limit throttles all of your users collectively instead of individually.
#   * Access logs record Cloudflare, which makes them useless for working out
#     what happened.
#
# `real_ip_header CF-Connecting-IP` fixes both — but only in combination with
# `set_real_ip_from`, which is what stops anyone else claiming to be a visitor
# by sending that header themselves. Trusting the header without the ranges is
# worse than not doing this at all.
#
# Cloudflare adds ranges occasionally; re-run after a change and reload.
set -eu

printf '# Generated by deploy/cloudflare-realip.sh — do not edit by hand.\n'
printf '# Source: https://www.cloudflare.com/ips-v4 and /ips-v6\n\n'

for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    curl -fsS "$url" | while read -r range; do
        [ -n "$range" ] && printf 'set_real_ip_from %s;\n' "$range"
    done
done

printf '\nreal_ip_header CF-Connecting-IP;\n'
